### ISSUE TITLE
Z Wave controller and Node.js version error

### ISSUE THREAD

**Issue by bradmcs** [createcandle/candle-controller#68]
I’m getting an error with the Z-Wave adapter on Candle 2.0.0 RC3:

> Failed to start add-on Z-Wave: The module ‘/home/pi/.webthings/addons/zwave-adapter/node_modules/@serialport/bindings/build/Release/bindings.node’ was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 83. Please try re-compiling or re-installing the module (for instance, using npm rebuild or npm install).

**Comment by flatsiedatsie** [comment]
Thanks. Maybe we should drop down to version 12 instead of 14 again. I'll try that in the next release candidate.

**Comment by flatsiedatsie** [comment]
Dropping down to version 12 lsolves the issue.

**Comment by flatsiedatsie** [comment]
Release candidate 4 is now available, which should solve this issue.

**Comment by bradmcs** [comment]
Great, thank you. I take it updates aren't happening yet and so I have to
reflash the sd card?

**Comment by flatsiedatsie** [comment]
At the moment, yes. The next step is to create a new version of the power-settings addon which will make it possible to run the install script and update your device.

Still, if possible I would recommend getting the latest disk image since it has a mayor change, a fourth disk partition, which at some point in the future might become a built-in rescue system. From RC4 onwards updates should become smooth sailing.
